theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  projects: 
    index:
      truncate_description: 0
  breadcrumb:
    position: after-hero